version: "3.7"

services:
  next-app:
    container_name: app
    image: tbmorton/mysite
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENC_VARIABLE}
    ports:
      - 80:80
