import * as React from 'react';

import Head from 'next/head'

// Joy UI Imports
import Appbar from '@/components/Appbar';
import { Box, CssBaseline } from '@mui/joy';

import { SidebarContext } from '@/components/common/sidebar';
import Post from '../../types/Post';
import { getPostInfoBySubject } from '@/lib/api';
import ApplicationMain from '@/components/ApplicationMain';
import { Map } from 'react-feather';
import PostList from '@/components/post_components/PostList';

type Props = {
  projectPosts: Post[],
}

export default function Projects({ projectPosts }: Props) {
  const {closeSidebar} = React.useContext(SidebarContext);
  React.useEffect(() => {
    closeSidebar();
  }, [])
  return (
    <Box sx={{ display: 'flex',  flexDirection: 'column', height: '100dvh'}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />
      <Appbar />
      <ApplicationMain slug={'travels'}>
        <PostList title={'My Travels'} icon={<Map size={'40px'}/>} posts={projectPosts}/>
      </ApplicationMain>
    </Box>
  )
}

export function getStaticProps() {
  const posts = getPostInfoBySubject('projects', [
    'title',
    'date',
    'slug',
    'excerpt',
    'author',
    'content',
    'ogImage',
    'coverImage',
  ])
  return {
    props: {
      projectPosts: posts
    }
  }
}
