import * as React from 'react';

import Head from 'next/head'

// Joy UI Imports
import Appbar from '@/components/Appbar';
import { Box, CssBaseline } from '@mui/joy';
import ApplicationMain from '@/components/ApplicationMain';
import { SidebarContext } from '@/components/common/sidebar';
import HomeContent from '@/components/home/HomeContent';

export default function Home() {
  const {closeSidebar} = React.useContext(SidebarContext);
  React.useEffect(() => {
    closeSidebar();
  }, [])

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', height: '100dvh'}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />
      <Appbar />
      {/*<Sidebar selected={'/'} />*/}
      <ApplicationMain slug={'/'} >
        <HomeContent />
      </ApplicationMain>
    </Box>
  )
}
